name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libssl-dev libffi-dev liblzma-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        pip install --upgrade pip cython buildozer

    - name: Accept Android Licenses and Build
      run: |
# إنشاء مجلد الرخص وقبولها تلقائياً
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # تثبيت وaccept رخص الـ SDK يدويامن خلال أداة سطر الأوامر
        yes | sdkmanager --licenses || true
        
        # بدء بناء التطبيق
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
